{{- if .Values.console.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "console.fullname" . }}-configuration
  labels:
    {{- include "console.labels" . | nindent 4 }}
data:
  application.yaml: |-
    {{- include "common.tplvalues.render" ( dict "value" .Values.console.configuration "context" $ ) | nindent 4 }}
  {{- if .Values.console.overrideConfiguration }}
  application-override.yaml: |-
    {{- if .Values.console.overrideConfiguration }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.console.overrideConfiguration "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
