{{- if .Values.camundaHub.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "camundaHub.fullname" . }}-configuration
  labels:
    {{- include "camundaHub.labels" . | nindent 4 }}
data:
  application.yaml: |-
    {{- if .Values.camundaHub.configuration }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.camundaHub.configuration "context" $ ) | nindent 4 }}
    {{- else }}
    # Camunda Hub Configuration
    # https://docs.camunda.io/docs/self-managed/
    camunda:
      hub:
        oAuth:
          audience: {{ .Values.global.identity.auth.camundaHub.audience | quote }}
          clientId: {{ .Values.global.identity.auth.camundaHub.clientId | quote }}
          issuer: {{ include "camundaPlatform.authIssuerUrlWithFallback" . | quote }}
          jwksUri: {{ include "camundaPlatform.authIssuerBackendUrlEndpointCerts" . | quote }}
          type: {{ include "camundaPlatform.authIssuerType" . | quote }}
        managed:
          method: plain
          releases:
            {{- include "camundaPlatform.releaseInfo" . | nindent 10 }}
    {{- end }}
  {{- if .Values.camundaHub.overrideConfiguration }}
  application-override.yaml: |-
    {{- if .Values.camundaHub.overrideConfiguration }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.camundaHub.overrideConfiguration "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
