{{- if and .Values.camundaHub.enabled .Values.camundaHub.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "camundaHub.serviceAccountName" . }}
  labels:
    {{- include "camundaHub.labels" . | nindent 4 }}
  {{- with .Values.camundaHub.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.camundaHub.serviceAccount.automountServiceAccountToken }}
{{- end }}
