{{- if .Values.webModeler.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webModeler.fullname" . }}-webapp-configuration
  labels: {{- include "webModeler.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
data:
  application.toml: |
    {{ tpl .Values.webModeler.webapp.configuration . | indent 4 | trim }}
  {{- range $key, $val := .Values.webModeler.webapp.extraConfiguration }}
  {{ $key }}: |
    {{ $val | indent 4 | trim }}
  {{- end }}
{{- end }}
