apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operate.fullname" . }}
  labels: {{- include "operate.labels" . | nindent 4 }}
  annotations: {{- toYaml  .Values.global.annotations | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "operate.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: 
        {{- include "operate.labels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
        {{- include "camundaPlatform.imagePullSecrets" . | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        {{- if .Values.image.tag }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.global.image.tag }}"
        {{- end }}
        env:
          {{- if .Values.global.identity.auth.enabled }}
          - name: SPRING_PROFILES_ACTIVE
            value: "identity-auth"
          - name: CAMUNDA_OPERATE_IDENTITY_ISSUER_URL
            value: {{ .Values.global.identity.auth.publicIssuerUrl | quote }}
          - name: CAMUNDA_OPERATE_IDENTITY_ISSUER_BACKEND_URL
            value: "http://{{ include "common.names.dependency.fullname" (dict "chartName" "keycloak" "chartValues" . "context" $) | trunc 20 | trimSuffix "-" }}:80/auth/realms/camunda-platform"
          - name: CAMUNDA_OPERATE_IDENTITY_CLIENT_ID
            value: "operate"
          - name: CAMUNDA_OPERATE_IDENTITY_CLIENT_SECRET
            {{- if and .Values.global.identity.auth.operate.existingSecret (not (typeIs "string" .Values.global.identity.auth.operate.existingSecret)) }}
            valueFrom:
              secretKeyRef:
                {{- /*
                    Helper: https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_secrets.tpl
                    Usage in keycloak secrets https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/secrets.yaml
                    and in statefulset https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/statefulset.yaml
                */}}
                name: {{ include "common.secrets.name" (dict "existingSecret" .Values.global.identity.auth.operate.existingSecret "context" $) }}
                key: operate-secret
            {{- else }}
            valueFrom:
              secretKeyRef:
                {{- /*
                    Helper: https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_secrets.tpl
                    Usage in keycloak secrets https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/secrets.yaml
                    and in statefulset https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/statefulset.yaml
                */}}
                name: {{ include "identity.secretNameOperateIdentity" . }}
                key: operate-secret
            {{- end }}
          - name: CAMUNDA_OPERATE_IDENTITY_AUDIENCE
            value: "operate-api"
          {{- else }}
          - name: SPRING_PROFILES_ACTIVE
            value: "auth"
          {{- end }}
        {{- if .Values.env}}
        {{ .Values.env | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.command}}
        command: {{ .Values.command }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/local/operate/config/application.yml
          subPath: application.yml
        {{- if .Values.extraVolumeMounts}}
        {{- .Values.extraVolumeMounts | toYaml | nindent 8 }}
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "operate.fullname" . }}
          defaultMode: {{ .Values.configMap.defaultMode }}
      {{- if .Values.extraVolumes}}
      {{- .Values.extraVolumes | toYaml | nindent 6 }}
      {{- end }}
      {{- if .Values.serviceAccount.name}}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
