#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: latest
    digest: "sha256:58ef531ef5aa1d0f5d928a3885c33bbd687fef1f93ae5a09f0d5e8bdc1c1f146"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.8-SNAPSHOT
    digest: "sha256:2fb6edc8038155587e1fb9b4a034749f4322685bd3764a5a228b377bf1fc9e55"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.8-SNAPSHOT
    digest: "sha256:44c6a9cbeccbcf293203c94fda3a2a8bd96b18141a5f6647925c37174e72ef92"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:7862bd54467ab4188a23f97d4752530fe833af34ce45d21cd662af9a9e494714"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: SNAPSHOT
      digest: "sha256:3e7d0953d1f4a5e94d18c628e0239c3c4a5313efdfb33c5e460476bab6a83dee"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:6d92f1294d81dcfa5597b1cbc0c3683854c288560ace5d2e8c9aa27d56ec847e"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.8-SNAPSHOT
    digest: "sha256:42ab5382bd8b7576918afa42473fe56cc433231b3f25ceb58b22faf926e29cbb"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.8-SNAPSHOT
    digest: "sha256:afd49763fe100d9ba07d017300393af0d2f39bc8033648a88f944ff085f061e8"
