#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: latest
    digest: "sha256:5cd48d252d3918066c6778bc44effde748f6cfcd7fd403ed5a2ae482bcc32cf7"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.8-SNAPSHOT
    digest: "sha256:730f7552fae5e7de9eb22de2560adf4d934665af261b69291cf65532db796f9f"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.8-SNAPSHOT
    digest: "sha256:bf9d5de3a0258e7b3f044e0ddc7a477b88f55b686ea032d458e54fedb472bf0b"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:0f2f815e35263a32af62efa70a216ce677a2712cf8748b873a188aabcf3d7175"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: SNAPSHOT
      digest: "sha256:32ba627810afd29eb284e35f4a5cd15297c963fa9ca3d69511f26b6ace71ee88"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:efaff177f345c6831b34703c1289a1f96fd38d6bb98f5f73fb30306d5a5dac68"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.8-SNAPSHOT
    digest: "sha256:eb92a367e04c7582e3bfa8934c61a4c617c84783716eabc8ac185491dfa51d8e"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.8-SNAPSHOT
    digest: "sha256:a8d59b7d8c84991a7877c09bbc730256428f383a7d11c2b522f63d422b3a1c56"
