#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: latest
    digest: "sha256:2bdb4ab272a6fff7e306b9e693d03e032b9186886b04d950dd01a1c5a5f41172"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.8-SNAPSHOT
    digest: "sha256:f0667b83258a803987569f5239648cd6f151a28381e93722b6e69467ee6f0ca0"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.8-SNAPSHOT
    digest: "sha256:ffe87562b5c3862befc9fa2eca3e4bcba6b1d5d7a8564c8efe17a9a733014d55"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: 8.8
      digest: "sha256:494ba6e95d3a4af47db27f7b78cea13efe2299de85c4d264bffef941d6abda2c"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: 8.8
      digest: "sha256:a1303d59644e755d08b976eb3adf408c3b95b354c80db923b50bd7709d8cacf9"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: 8.8
      digest: "sha256:d17482036f48a178dc2b68c09a26841546b804e81be3ccb626eb9d538ed06d12"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.8-SNAPSHOT
    digest: "sha256:5b540dd9a433047f44cc2d7bbb43381d89861078dbfd5f101c3fd005922d1b2e"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.8-SNAPSHOT
    digest: "sha256:c72974b2a833744c81b33e939b9fa4f95320cd20f3dd221bbefc897f1fbe035c"
