global:
  ingress:
    enabled: true
    className: nginx
    # The Ingress host will be added via CLI.
    host: "bkenez.ci.distro.ultrawombat.com"
    tls:
      enabled: true
      # A wildcard certificate will be used.
      secretName: camunda-platform
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "{{ .Values.global.ingress.host }}"
      external-dns.alpha.kubernetes.io/ttl: "60"
  security:
    authentication:
      method: oidc
  identity:
    auth:
      enabled: true
      publicIssuerUrl: "https://{{ .Values.global.ingress.host }}/auth/realms/camunda-platform"
      admin:
        enabled: true
        existingSecret:
          name: "integration-test-credentials"
      #######################
      # Management Group
      #######################
      webModeler:
        redirectUrl: "https://{{ .Values.global.ingress.host }}/modeler"
      console:
        redirectUrl: "https://{{ .Values.global.ingress.host }}"
        existingSecret:
          name: "integration-test-credentials"
      #######################
      # Orchestration Group
      #######################
      core:
        redirectUrl: "https://{{ .Values.global.ingress.host }}/core"
        existingSecret:
          name: "integration-test-credentials"
      connectors:
        existingSecret:
          name: "integration-test-credentials"
      optimize:
        redirectUrl: "https://{{ .Values.global.ingress.host }}/optimize"
        existingSecret:
          name: "integration-test-credentials"
    
webModeler: 
  enabled: true
  contextPath: "/modeler"
  restapi:
    mail:
      # This value is required, otherwise the restapi pod wouldn't start.
      fromAddress: noreply@example.com
    externalDatabase: 
      url: "jdbc:postgresql://modeler-db-postgresql:5432/webmodeler-test"
      user: postgres
      password: "VXzayYBd8T"

# WebModeler Database.
webModelerPostgresql:
  enabled: false
  auth:
    existingSecret: "integration-test-credentials"
    secretKeys:
      adminPasswordKey: "webmodeler-postgresql-admin-password"
      userPasswordKey: "webmodeler-postgresql-user-password"


optimize:
  contextPath: "/optimize"

connectors:
  contextPath: "/connectors"

elasticsearch:
  maxUnavailable: 0

identity:
  enabled: true
  contextPath: "/identity"
  firstUser:
    existingSecret: "integration-test-credentials"

identityKeycloak:
  enabled: true
  postgresql:
    auth:
      existingSecret: "integration-test-credentials"
      secretKeys:
        adminPasswordKey: "identity-keycloak-postgresql-admin-password"
        userPasswordKey: "identity-keycloak-postgresql-user-password"
  auth:
    existingSecret: "integration-test-credentials"
    passwordSecretKey: "identity-keycloak-admin-password"

core:
  contextPath: "/core"
  ingress:
    grpc:
      enabled: true
      className: nginx
      host: "grpc-{{ .Values.global.ingress.host }}"
      tls:
        enabled: true
        # A wildcard certificate will be used.
        secretName: camunda-platform-zeebe-gateway
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "core-{{ .Values.global.ingress.host }}"
        external-dns.alpha.kubernetes.io/ttl: "60"
  # giving access to venom to deploy a model. Given access to connectors
  # TODO: Find a way to only give connectors read access
  env:
    - name: CAMUNDA_SECURITY_INITIALIZATION_MAPPINGS_0_MAPPINGID
      value: "demo-user-mapping"
    - name: CAMUNDA_SECURITY_INITIALIZATION_MAPPINGS_0_CLAIMNAME
      value: "preferred_username"
    - name: CAMUNDA_SECURITY_INITIALIZATION_MAPPINGS_0_CLAIMVALUE
      value: "demo"
    - name: CAMUNDA_SECURITY_INITIALIZATION_MAPPINGS_1_MAPPINGID
      value: "venom-client-mapping"
    - name: CAMUNDA_SECURITY_INITIALIZATION_MAPPINGS_1_CLAIMNAME
      value: "client_id"
    - name: CAMUNDA_SECURITY_INITIALIZATION_MAPPINGS_1_CLAIMVALUE
      value: "venom"
    - name: CAMUNDA_SECURITY_INITIALIZATION_MAPPINGS_2_MAPPINGID
      value: "connectors-client-mapping"
    - name: CAMUNDA_SECURITY_INITIALIZATION_MAPPINGS_2_CLAIMNAME
      value: "client_id"
    - name: CAMUNDA_SECURITY_INITIALIZATION_MAPPINGS_2_CLAIMVALUE
      value: "connectors"
    - name: CAMUNDA_SECURITY_INITIALIZATION_DEFAULTROLES_ADMIN_MAPPINGS_0
      value: "demo-user-mapping"
    - name: CAMUNDA_SECURITY_INITIALIZATION_DEFAULTROLES_ADMIN_MAPPINGS_1
      value: "venom-client-mapping"
    - name: CAMUNDA_SECURITY_INITIALIZATION_DEFAULTROLES_ADMIN_MAPPINGS_2
      value: "connectors-client-mapping"


console:
  contextPath: "/console"
  