#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: latest
    digest: "sha256:322e3bb298e677d609a677565f62841322e96deb50f9ffdf3a38ee11bdf6bac2"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.8-SNAPSHOT
    digest: "sha256:cd311330a6a60501ca0277641f444d551f8a21508c7199c9072b3bbdec1d4230"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.8-SNAPSHOT
    digest: "sha256:44c6a9cbeccbcf293203c94fda3a2a8bd96b18141a5f6647925c37174e72ef92"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:a825ac769ac02519900f4b2bd0a45def52be7f7856b1fa7ff707fe1efeb647e9"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: SNAPSHOT
      digest: "sha256:e9e32c355fc3dae2d3197215ce1296094e4daf3c81b3f22489e1ea0a3bfeb8ce"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:354ae37723c097a2f25850e6952ce309729c40502dda35df1094a5e00e731661"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.8-SNAPSHOT
    digest: "sha256:4373ac55b50be0d334146344933d99bd903b5085e45c11df339e08e154bc2069"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.8-SNAPSHOT
    digest: "sha256:12931539bb2680f6dc7785a3d8654ff2987d87728d8aec5d5942712062b93650"
