#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: latest
    digest: "sha256:501de481e2551f6f60d96a8e03841ddbc681c4170656cada72ed86ca5884f977"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.8.8
    digest: "sha256:61e1c19090bea011154c8d39e6764a0309b29d38388e775c0d6c0010b19d5c07"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.8.6
    digest: "sha256:73908ec35d6a9d093e2579e47034461ce7a25563d55bfaec9e9390adb6949b5e"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: 8.8
      digest: "sha256:b6023782b192539903f1c8c6e91d838692faa9c430654e039edc9db04156c96c"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: 8.8
      digest: "sha256:f72875a6bf82a421fd2f0c7438146f0edde0014684e6c8b947ad064006ed1b21"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: 8.8
      digest: "sha256:5744331018423528a26809016932ed8feae5912b59266b78c7f2af94a096f8fc"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.8.14
    digest: "sha256:03e3a8ed498a09c5cd8dea676dc158dd9c2b6176a0c944ba05a0cdadd6316a81"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.8.8
    digest: "sha256:fe6b8fde26f02b774c67f8439dcd1145c3e9604b3a51797c6ad56fe86a3b0844"
