#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: latest
    digest: "sha256:5de75f5974fe51aa582020d5188c4dbf94df9bb8fa11d2a7dbb95031bba32fc4"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.8-SNAPSHOT
    digest: "sha256:07a38db5825de19750fc6044359b670d052dc6e4d53952580787c5c956efddb6"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.8-SNAPSHOT
    digest: "sha256:44c6a9cbeccbcf293203c94fda3a2a8bd96b18141a5f6647925c37174e72ef92"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:aa60af91508da7a482d85d349531f9f2e6ab4972b139ece21a2dd66da56c9dc6"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: SNAPSHOT
      digest: "sha256:190e83abeaba7d86a791ebd0eedbfb21fabae9c6f96da323e9874610702ea58b"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:a29e61624169bfaa4c0774e60142847a68bdcbef5002338c2b45cb5df61e8e80"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.8-SNAPSHOT
    digest: "sha256:d88865e50c2013e3df17dab31bea03a259b7ffe4c345f38d7392be4b25a871b4"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.8-SNAPSHOT
    digest: "sha256:fd7fbb48f8aef847f4a9cba8ecab817bb763ec3f034fa64684fd7e7c9b5c4bd3"
