#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: latest
    digest: "sha256:bc6fa3d65b52b64245a90a175e4b6316a0a94c8c7ebcbeacdc656dea980c08e1"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: SNAPSHOT
    digest: "sha256:aa70b26705cf059e9248809bc54625cd8f2346e6fa8ab5592560b65c2f45e1b0"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.8-SNAPSHOT
    digest: "sha256:209ded9f913585ba823839952a72e57a9c749ba902435c461277c27b0cc0f7bb"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:8899b51269beec95053bb055ed1178d0473f712ece75d5c4d12cd368ded262be"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: SNAPSHOT
      digest: "sha256:94132723ba1705225205083681aacea4a9ba1b12da57b5cb6e78c07c34b42112"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:e20e2a8544e9d3e599f21c7fc0225cb73b34af7de6af5e241516d46608429236"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.8-SNAPSHOT
    digest: "sha256:18ed5a55393f008fc96bfdc77940a3ca394511bdd1f0e755b04bceb56d745468"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.8-SNAPSHOT
    digest: "sha256:75dbdde615d6b0bf657f11edf7c4ece3f1ee3f4e110bfc25f6e7487333b44d90"
