#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: latest
    digest: "sha256:39084d67f612470bc3cd88d4caca03aeb5b4004279a1ceb114ec5096cda5d614"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: SNAPSHOT
    digest: "sha256:918b0e5090117fc7f66607627d1144a670ebd7efa1dc0cc647a052bef4aa63f7"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.8-SNAPSHOT
    digest: "sha256:45930f34088c57d8a57c348cb664a0862ae5c4c5ce2ecb9e5ef2b4b453d883ab"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:27c7322e2fd1ca68076d017659ef7a94412c66c5e039af9d16e5e3c6d29050fc"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: SNAPSHOT
      digest: "sha256:7a0fd75f2fa723d6ed9cb8c3b25836e9beb4696453e84f71ece0f4e474a9bd70"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:9d46706407595c7d48553ff8c35b1ab91b4936f110b6871a5f92783e800f6114"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.8-SNAPSHOT
    digest: "sha256:21eb11c1219068ec659a8b8d2d34124107ff1452c2225d286e55fc1cc6df158b"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:abb94a3530715095f301f0149dab5696e352740b7a111741da65d912eacecd01"
