apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  {{- end }}
  name: {{ include "webModeler.websockets.fullname" . }}
  labels: {{- include "webModeler.websockets.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "webModeler.websockets.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "webModeler.websockets.labels" . | nindent 8 }}
      {{- if .Values.websockets.podLabels }}
      {{- toYaml .Values.websockets.podLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.websockets.podAnnotations }}
      annotations:
        {{- toYaml .Values.websockets.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      imagePullSecrets:
        {{- include "camundaPlatform.imagePullSecrets" . | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}-websockets
        image: {{ include "webModeler.websockets.image" . | quote }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        {{- if .Values.websockets.containerSecurityContext }}
        securityContext: {{- toYaml .Values.websockets.containerSecurityContext | nindent 10 }}
        {{- end }}
        env:
          - name: APP_NAME
            value: "Web Modeler WebSockets"
          - name: PUSHER_APP_ID
            valueFrom:
              configMapKeyRef:
                name: {{ include "webModeler.fullname" . }}
                key: pusher-app-id
          - name: PUSHER_APP_KEY
            valueFrom:
              configMapKeyRef:
                name: {{ include "webModeler.fullname" . }}
                key: pusher-app-key
          - name: PUSHER_APP_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "webModeler.fullname" . }}
                key: pusher-app-secret
          - name: PUSHER_APP_CLUSTER
            value: "web-modeler"
        {{- with .Values.websockets.env }}
            {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- if .Values.websockets.command}}
        command: {{ .Values.websockets.command }}
        {{- end }}
        resources:
          {{- toYaml .Values.websockets.resources | nindent 10 }}
        ports:
        - containerPort: 8060
          name: http
          protocol: TCP
      {{- if .Values.serviceAccount.name}}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      {{- if .Values.websockets.podSecurityContext }}
      securityContext: {{- toYaml .Values.websockets.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- with .Values.websockets.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.websockets.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.websockets.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
