apiVersion: v1
kind: Secret
metadata:
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  name: {{ include "webModeler.fullname" . }}
  labels: {{- include "webModeler.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
type: Opaque
data:
  pusher-app-secret: {{ randAlphaNum 20 | b64enc }}
