---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: camunda-helm-existing-secrets-8-8
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: distribution-team
  target:
    name: integration-test-credentials  # name of the k8s Secret to be created
  data:
    # Core secrets
    - secretKey: client-secret
      remoteRef:
        key: integration-test
        property: client-secret
    - secretKey: entra-child-app-client-secret
      remoteRef:
        key: integration-test
        property: entra-child-app-client-secret

    # Component authentication secrets

    # Identity authentication secrets
    - secretKey: identity-firstuser-password
      remoteRef:
        key: integration-test
        property: identity-firstuser-password
    - secretKey: identity-admin-client-token
      remoteRef:
        key: integration-test
        property: password
    - secretKey: identity-connectors-client-token
      remoteRef:
        key: integration-test
        property: password
    - secretKey: identity-console-client-token
      remoteRef:
        key: integration-test
        property: password
    - secretKey: identity-orchestration-client-token
      remoteRef:
        key: integration-test
        property: password
    - secretKey: identity-optimize-client-token
      remoteRef:
        key: integration-test
        property: password
    - secretKey: identity-keycloak-admin-password
      remoteRef:
        key: integration-test
        property: password
    - secretKey: identity-keycloak-postgresql-admin-password
      remoteRef:
        key: integration-test
        property: password
    - secretKey: identity-keycloak-postgresql-user-password
      remoteRef:
        key: integration-test
        property: password
    - secretKey: identity-postgresql-admin-password
      remoteRef:
        key: integration-test
        property: password
    - secretKey: identity-postgresql-user-password
      remoteRef:
        key: integration-test
        property: password

    # Infrastructure passwords
    - secretKey: admin-password
      remoteRef:
        key: integration-test
        property: admin-password
    - secretKey: password
      remoteRef:
        key: integration-test
        property: password
    - secretKey: smtp-password
      remoteRef:
        key: integration-test
        property: smtp-password

    # WebModeler PostgreSQL
    - secretKey: web-modeler-postgresql-admin-password
      remoteRef:
        key: integration-test
        property: password
    - secretKey: web-modeler-postgresql-user-password
      remoteRef:
        key: integration-test
        property: password
