---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: camunda-helm-existing-secrets-infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: infra-credentials  # name of the k8s Secret to be created
  data:
  - secretKey: keycloak-admin-password
    remoteRef:
      key: products/distribution/ci/integration-test
      property: keycloak-admin-password
  - secretKey: elasticsearch-password
    remoteRef:
      key: products/distribution/ci/integration-test
      property: elasticsearch-password
  - secretKey: kibana-password
    remoteRef:
      key: products/distribution/ci/integration-test
      property: kibana-password
