#
# Camunda - Latest
#

global:
  # https://github.com/camunda/camunda-platform/releases
  # https://hub.docker.com/u/camunda
  image:
    # renovate: datasource=docker depName=camunda/zeebe
    tag: 8.4.1

zeebe:
  # https://github.com/camunda/zeebe/releases
  # https://hub.docker.com/r/camunda/zeebe
  image:
    # renovate: datasource=docker depName=camunda/zeebe
    tag: 8.4.1
    
operate:
  # https://github.com/camunda/operate/releases
  # https://hub.docker.com/r/camunda/operate
  image:
    # renovate: datasource=docker depName=camunda/operate
    tag: 8.4.1

tasklist:
  # https://github.com/camunda/tasklist/blob/master/CHANGELOG.md
  # https://hub.docker.com/r/camunda/tasklist
  image:
    # renovate: datasource=docker depName=camunda/tasklist
    tag: 8.4.1

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.4.3

identity:
  # https://github.com/camunda-cloud/identity/releases
  # https://hub.docker.com/r/camunda/identity
  image:
    # renovate: datasource=docker depName=camunda/identity
    tag: 8.4.3

  keycloak:
    # https://hub.docker.com/r/bitnami/keycloak/tags
    image:
      repository: bitnami/keycloak
      tag: 22.0.5
    postgresql:
      # https://hub.docker.com/r/bitnami/postgresql/tags
      image:
        repository: bitnami/postgresql
        tag: 15.5.0

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    # renovate: datasource=docker depName=camunda/optimize
    tag: 8.4.0

webModeler:
  # Camunda Enterprise repository.
  # registry.camunda.cloud/web-modeler-ee
  image:
    # renovate: datasource=docker depName=camunda/web-modeler lookupName=registry.camunda.cloud/web-modeler-ee/modeler-restapi
    tag: 8.4.1

#
# Elasticsearch
#

elasticsearch:
  # https://hub.docker.com/r/bitnami/elasticsearch/tags
  image:
    repository: bitnami/elasticsearch
    tag: 8.9.2
