#
# Camunda Platform - Latest
#

global:
  # https://github.com/camunda/camunda-platform/releases
  # https://hub.docker.com/u/camunda
  image:
    # renovate: datasource=github-releases depName=camunda/camunda-platform
    tag: 8.3.0

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 0.23.2

identity:
  keycloak:
    # https://hub.docker.com/r/bitnami/keycloak/tags
    image:
      repository: bitnami/keycloak
      tag: 22.0.4
    postgresql:
      # https://hub.docker.com/r/bitnami/postgresql/tags
      image:
        repository: bitnami/postgresql
        tag: 15.4.0

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 3.10.6

webModeler:
  # Camunda Enterprise repository.
  # registry.camunda.cloud/web-modeler-ee
  image:
    # renovate: datasource=docker depName=camunda/web-modeler lookupName=registry.camunda.cloud/web-modeler-ee/modeler-restapi
    tag: 8.3.0

#
# Elasticsearch
#

elasticsearch:
  # https://hub.docker.com/r/bitnami/elasticsearch/tags
  image: bitnami/elasticsearch
  tag: 8.10.2
