#
# Camunda - Latest
#

global:
  # https://github.com/camunda/camunda-platform/releases
  # https://hub.docker.com/u/camunda
  image:
    # renovate: datasource=github-releases depName=camunda/camunda-platform
    tag: 8.5.0

console:
  # Camunda Enterprise repository.
  # registry.camunda.cloud/console
  image:
    # renovate: datasource=docker depName=camunda/console lookupName=registry.camunda.cloud/console/console-sm
    tag: 8.5.22

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.5.0

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    # renovate: datasource=docker depName=camunda/optimize
    tag: 8.5.0

webModeler:
  # Camunda Enterprise repository.
  # registry.camunda.cloud/web-modeler-ee
  image:
    # renovate: datasource=docker depName=camunda/web-modeler lookupName=registry.camunda.cloud/web-modeler-ee/modeler-restapi
    tag: 8.5.0

#
# Identity - Keycloak
#

identityKeycloak:
  # https://hub.docker.com/r/bitnami/keycloak/tags
  image:
    repository: bitnami/keycloak
    tag: 23.0.7
  postgresql:
    # https://hub.docker.com/r/bitnami/postgresql/tags
    image:
      repository: bitnami/postgresql
      tag: 15.6.0

#
# Elasticsearch
#

elasticsearch:
  # https://hub.docker.com/r/bitnami/elasticsearch/tags
  image:
    repository: bitnami/elasticsearch
    tag: 8.12.2
