#
# Camunda - v8.4
# https://docs.camunda.io/docs/next/reference/announcements/#camunda-84
#

global:
  # https://github.com/camunda/camunda-platform/releases
  # https://hub.docker.com/u/camunda
  image:
    # renovate: datasource=github-releases depName=camunda/camunda-platform
    tag: 8.4.6

console:
  # Camunda Enterprise repository.
  # registry.camunda.cloud/console
  image:
    # renovate: datasource=docker depName=camunda/console lookupName=registry.camunda.cloud/console/console-sm
    tag: 8.4.60

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.4.7

identity:
  keycloak:
    # https://hub.docker.com/r/bitnami/keycloak/tags
    image:
      repository: bitnami/keycloak
      tag: 22.0.5
    postgresql:
      # https://hub.docker.com/r/bitnami/postgresql/tags
      image:
        repository: bitnami/postgresql
        tag: 15.5.0

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    # renovate: datasource=docker depName=camunda/optimize
    tag: 8.4.4

webModeler:
  # Camunda Enterprise repository.
  # registry.camunda.cloud/web-modeler-ee
  image:
    # renovate: datasource=docker depName=camunda/web-modeler lookupName=registry.camunda.cloud/web-modeler-ee/modeler-restapi
    tag: 8.4.4

#
# Elasticsearch
#

elasticsearch:
  # https://hub.docker.com/r/bitnami/elasticsearch/tags
  image:
    repository: bitnami/elasticsearch
    tag: 8.9.2
