{{- if and .Values.optimize.enabled (not .Values.global.noSecondaryStorage) -}}
kind: ConfigMap
metadata:
  name: {{ include "optimize.fullname" . }}-configuration
  labels:
    {{- include "optimize.labels" . | nindent 4 }}
apiVersion: v1
data:
  environment-config.yaml: |
    {{ tpl .Values.optimize.configuration . | indent 4 | trim }}
  {{- if .Values.global.identity.auth.enabled }}
  application-ccsm.yaml: |
    camunda:
      identity:
        clientId: {{ include "optimize.authClientId" . | quote }}
        audience: {{ include "optimize.authAudience" . | quote }}
        issuer: {{ include "camundaPlatform.authIssuerUrlWithFallback" . | quote }}
        issuerBackendUrl: {{ include "camundaPlatform.authIssuerBackendUrl" . | quote }}
  {{- end }}

  {{- range $key, $val := .Values.optimize.extraConfiguration }}
  {{ $key }}: |
    {{ $val | indent 4 | trim }}
  {{- end }}
{{- end }}
