{{- if and .Values.optimize.enabled (not .Values.global.noSecondaryStorage) -}}
kind: ConfigMap
metadata:
  name: {{ include "optimize.fullname" . }}-configuration
  labels:
    {{- include "optimize.labels" . | nindent 4 }}
apiVersion: v1
data:
  environment-config.yaml: |
    {{- $base := dict }}
    {{- if .Values.optimize.configuration }}
    {{- $base = .Values.optimize.configuration | fromYaml }}
    {{- else }}
    {{- $base = include "optimize.defaultConfig" . | fromYaml }}
    {{- end }}
    {{- range .Values.optimize.extraConfiguration }}
    {{- $parsed := .content | fromYaml }}
    {{- $base = mustMergeOverwrite $base $parsed }}
    {{- end }}
    {{- $base | toYaml | nindent 4 }}

  {{- if .Values.global.identity.auth.enabled }}
  application-ccsm.yaml: |
    camunda:
      identity:
        clientId: {{ include "optimize.authClientId" . | quote }}
        audience: {{ include "optimize.authAudience" . | quote }}
        issuer: {{ include "camundaPlatform.authIssuerUrlWithFallback" . | quote }}
        issuerBackendUrl: {{ include "camundaPlatform.authIssuerBackendUrl" . | quote }}
  {{- end }}

{{- end }}
