{{ if and .Values.core.enabled .Values.core.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "core.fullname" . }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
spec:
  {{- if .Values.core.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.core.podDisruptionBudget.minAvailable | default 0 }}
  {{- else }}
  maxUnavailable: {{ .Values.core.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "core.matchLabels" . | nindent 6 }}
{{- end }}
