#
# Camunda - v8.3
# https://docs.camunda.io/docs/next/reference/announcements/#camunda-83
#

global:
  # https://github.com/camunda/camunda-platform/releases
  # https://hub.docker.com/u/camunda
  image:
    # renovate: datasource=docker depName=camunda/zeebe
    tag: 8.3.11

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.3.12

identity:
  keycloak:
    # https://hub.docker.com/r/bitnami/keycloak/tags
    image:
      repository: bitnami/keycloak
      tag: 22.0.5
    postgresql:
      # https://hub.docker.com/r/bitnami/postgresql/tags
      image:
        repository: bitnami/postgresql
        tag: 15.5.0

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    # renovate: datasource=docker depName=camunda/optimize
    tag: 8.3.10

webModeler:
  # Camunda Enterprise repository.
  # registry.camunda.cloud/web-modeler-ee
  image:
    # renovate: datasource=docker depName=camunda/web-modeler lookupName=registry.camunda.cloud/web-modeler-ee/modeler-restapi
    tag: 8.3.7

#
# Elasticsearch
#

elasticsearch:
  # https://hub.docker.com/r/bitnami/elasticsearch/tags
  image:
    repository: bitnami/elasticsearch
    tag: 8.14.0