#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.9-SNAPSHOT
    digest: "sha256:e90ad20bbc936ab123a4343a1a3cf88e4cd839b22a2c5b5dedfcc7b5b478c659"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: SNAPSHOT
    digest: "sha256:d93793bacf5ebf76ddd7cd6237ad3e72497d4746c2e66143690e473c43b0622d"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8-latest
    digest: "sha256:2b4350b56d177c3cf027f71083bbf0d1f1311fcebafaa01afedc8ddbce639323"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:4700ea03fd2192b34df7e03a7f95ad737cf78ba93b3d0131c4a1153b722cb0f1"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: SNAPSHOT
      digest: "sha256:9fc84050d7b542e7d0521a335b882a2f86d04db3fc1405e36dc622c7fbe3ae99"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:4a3f95e5cb287f71de454f5bb4f31dcabeec1aabc960d77226d83a477f83882a"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: SNAPSHOT
    digest: "sha256:4d59774c379ec6997466ba2e04a48d9decaebda17a4ab56ed6a7ce54e5939dfb"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:e196718875fc86bf14a1444ae3785a9adbf446b080dcfe6f98480945146a641c"
