#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.9-SNAPSHOT
    digest: "sha256:f310967b71aaa8e780237ae5ca02c3bc941ba37e4cb37373b6ec690612418a2e"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: SNAPSHOT
    digest: "sha256:826f79e19ee870375723900ccb4915860b2ce6da0d7bb7750a0db7f4bdccfe71"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8-latest
    digest: "sha256:ee002dd212ddababaa2a6d09039e64b10e4ffc318f7a7721981f2b829bb14dd8"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:2e380637b6a2e8172dad2cce2f98bc2a9a85acdc9c50e13f767eaef6ef17caf6"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: SNAPSHOT
      digest: "sha256:25919129b22b01ce18b73210eae5a27c7a8f849be12aea0022c196a07f7b9020"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:204866e8da3c2250cb6442a395fb7907b03d6cd0c9589abe301ae925a5cbaf0a"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: SNAPSHOT
    digest: "sha256:20f5c9ecfc98ad4a1abd3b0a2116e246b2a759903ce9c282a884ebe0ec9d5e5b"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:b37ec6f1665e0b86ea02cd15ecb062832902bcd01ff89e45a5d5e901eb2eca81"
