connectors:
  image:
    repository: camunda/connectors-bundle
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000

operate:
  image:
    repository: camunda/operate
    digest: sha256:1111111111111111111111111111111111111111111111111111111111111111

tasklist:
  image:
    repository: camunda/tasklist
    digest: sha256:2222222222222222222222222222222222222222222222222222222222222222

optimize:
  image:
    repository: camunda/optimize
    digest: sha256:3333333333333333333333333333333333333333333333333333333333333333

identity:
  image:
    repository: camunda/identity
    digest: sha256:4444444444444444444444444444444444444444444444444444444444444444

zeebe:
  image:
    repository: camunda/zeebe
    digest: sha256:5555555555555555555555555555555555555555555555555555555555555555

zeebeGateway:
  image:
    repository: camunda/zeebe
    digest: sha256:5555555555555555555555555555555555555555555555555555555555555555