global:
  zeebe: "{{ .Release.Name }}-zeebe"
  elasticsearch:
    host: "elasticsearch-master"
    port: 9200
    clusterName: "elasticsearch"

logging:
  level:
    ROOT: INFO
    org.camunda.tasklist: DEBUG

service:
  type: ClusterIP
  port: 80
image:
  repository: camunda/tasklist
  tag: 1.1.2

resources: 
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"    
  path: /
  host:
