{{- if and .Values.prometheusServiceMonitor.enabled .Values.core.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "camundaPlatform.fullname" . }}-core
  labels: {{- include "camundaPlatform.labels" . | nindent 4 }}
    {{- toYaml .Values.prometheusServiceMonitor.labels | nindent 4}}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.global.labels | nindent 6 }}
      app.kubernetes.io/component: core
  endpoints:
    - honorLabels: true
      path: {{ .Values.core.contextPath }}{{ .Values.core.metrics.prometheus }}
      port: http
      interval: {{ .Values.prometheusServiceMonitor.scrapeInterval }}
{{- end }}
