{{- if and .Values.global.gateway.enabled (not .Values.global.gateway.external) -}}
{{- if .Values.identityKeycloak.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "camundaPlatform.fullname" . }}-keycloak
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.global.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.tplvalues.merge-overwrite" (dict
      "values" (list
        (include "camundaPlatform.labels" .)
        .Values.global.gateway.labels
      )
      "context" .
    ) | nindent 4 }}
spec:
  parentRefs:
  - name: {{ include "camundaPlatform.fullname" . }}
    sectionName: {{ if .Values.global.gateway.tls.enabled }}https{{ else }}http{{ end }}
  hostnames:
  - {{ tpl .Values.global.host $ | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ include "identity.keycloak.contextPath" . | trimSuffix "/" }}/
    backendRefs:
    - name: {{ include "identity.keycloak.service" . }}
      namespace: {{ .Release.Namespace }}
      port: {{ include "identity.keycloak.port" . }}
---
{{- end }}
{{- if .Values.identity.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "camundaPlatform.fullname" . }}-identity
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.global.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.tplvalues.merge-overwrite" (dict
      "values" (list
        (include "camundaPlatform.labels" .)
        .Values.global.gateway.labels
      )
      "context" .
    ) | nindent 4 }}
spec:
  parentRefs:
  - name: {{ include "camundaPlatform.fullname" . }}
    sectionName: {{ if .Values.global.gateway.tls.enabled }}https{{ else }}http{{ end }}
  hostnames:
  - {{ tpl .Values.global.host $ | quote }}
  rules:
  - matches:
    - path:
        type: Exact
        value: {{ trimSuffix "/" .Values.identity.contextPath }}
    filters:
    - type: URLRewrite
      urlRewrite:
        hostname: {{ .Values.global.host }}
        path:
          type: ReplaceFullPath
          replaceFullPath: {{ trimSuffix "/" .Values.identity.contextPath }}/
    backendRefs:
      - name: {{ template "identity.fullname" . }}
        namespace: {{ .Release.Namespace }}
        port: {{ .Values.identity.service.port }}
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.identity.contextPath }}
    backendRefs:
    - name: {{ template "identity.fullname" . }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.identity.service.port }}
{{- end }}
{{- end }}
