#
# Enterprise Bitnami-based images
# These images are derived from Bitnami opensource, include CVE patches and extended support,
# and are hosted on a private registry. Access is restricted to Enterprise users only.
#
# Kubernetes secret for accessing registry.camunda.cloud (must be created manually):
#
# Create the secret using:
# kubectl create secret docker-registry camunda-registry-secret \
#   --docker-server=registry.camunda.cloud \
#   --docker-username=<your-username> \
#   --docker-password=<your-password> \
#   --docker-email=unused@example.com
#
# Replace <your-username> and <your-password> with your LDAP credentials.
#
# For more details on using pullSecrets in pods:
# https://kubernetes.io/docs/concepts/containers/images/#specifying-pullSecrets-on-a-pod

# TODO: add missing metrics elasticsearch + postgresql metrics + keycloakConfigCli

identityPostgresql:
  image:
    registry: registry.camunda.cloud
    repository: vendor-ee/postgresql
    tag: 15.10.0-debian-12-r2
    pullSecrets:
      - name: camunda-registry-secret
  volumePermissions:
    image:
      registry: registry.camunda.cloud
      repository: vendor-ee/os-shell
      pullSecrets:
        - name: camunda-registry-secret  

identityKeycloak:
  image:
    registry: registry.camunda.cloud
    repository: keycloak-ee/keycloak
    tag: 25.0.6
    pullSecrets:
      - name: camunda-registry-secret
  postgresql:
    image:
      registry: registry.camunda.cloud
      repository: vendor-ee/postgresql
      tag: 15.10.0-debian-12-r2
      pullSecrets:
        - name: camunda-registry-secret
    volumePermissions:
      image:
        registry: registry.camunda.cloud
        repository: vendor-ee/os-shell
        pullSecrets:
          - name: camunda-registry-secret  

postgresql:
  image:
    registry: registry.camunda.cloud
    repository: vendor-ee/postgresql
    tag: 14.18.0-debian-12-r0
    pullSecrets:
      - name: camunda-registry-secret
  volumePermissions:
    image:
      registry: registry.camunda.cloud
      repository: vendor-ee/os-shell
      pullSecrets:
        - name: camunda-registry-secret  

elasticsearch:
  image:
    registry: registry.camunda.cloud
    repository: vendor-ee/elasticsearch
    tag: 8.15.4
    pullSecrets:
      - name: camunda-registry-secret
  volumePermissions:
    image:
      registry: registry.camunda.cloud
      repository: vendor-ee/os-shell
      pullSecrets:
        - name: camunda-registry-secret  
  sysctlImage:
    image:
      registry: registry.camunda.cloud
      repository: vendor-ee/os-shell
      pullSecrets:
        - name: camunda-registry-secret  

