{{- if .Values.console.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.console.replicaCount }}
  selector:
    matchLabels:
      {{- include "console.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.console.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "console.matchLabels" . | nindent 8 }}
    spec:
      {{- with .Values.console.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "console.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.console.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.console.securityContext | nindent 12 }}
          image: {{ include "camundaPlatform.imageByParams" (dict "base" .Values.global "overlay" .Values.console) }}
          imagePullPolicy: {{ .Values.console.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: prod
            - name: IDENTITY_BASE
              value: {{ include "camundaPlatform.authIssuerUrl" . | quote }}
            - name: IDENTITY_ISSUER_URL
              value: {{ include "camundaPlatform.authIssuerUrl" . | quote }}
            - name: IDENTITY_REALM
              value: camunda-platform
            - name: IDENTITY_AUDIENCE
              value: console
            - name: IDENTITY_CLIENT_ID
              value: console
          {{- if .Values.console.env}}
            {{ .Values.console.env | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.console.service.port }}
              protocol: TCP
            - name: management
              containerPort: {{ .Values.console.service.managementPort }}
              protocol: TCP
          {{- if .Values.console.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.console.startupProbe.probePath }}
              scheme: {{ .Values.console.startupProbe.scheme }}
              port: management
            initialDelaySeconds: {{ .Values.console.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.console.startupProbe.periodSeconds }}
            successThreshold: {{ .Values.console.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.console.startupProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.console.startupProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.console.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.console.readinessProbe.probePath }}
              scheme: {{ .Values.console.readinessProbe.scheme }}
              port: management
            initialDelaySeconds: {{ .Values.console.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.console.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.console.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.console.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.console.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.console.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.console.livenessProbe.probePath }}
              scheme: {{ .Values.console.livenessProbe.scheme }}
              port: management
            initialDelaySeconds: {{ .Values.console.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.console.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.console.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.console.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.console.livenessProbe.timeoutSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.console.resources | nindent 12 }}
          volumeMounts:
            - name: console-configuration
              mountPath: /var/run/config
          {{- if .Values.console.extraVolumeMounts }}
            {{- .Values.console.extraVolumeMounts | toYaml | nindent 12 }}
          {{- end }}
      volumes:
        - name: console-configuration
          configMap:
            name: {{ include "console.fullname" . }}-configuration
      {{- if .Values.console.extraVolumes }}
        {{- .Values.console.extraVolumes | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.console.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.console.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.console.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
