{{- if and .Values.global.gateway.enabled (not .Values.global.gateway.external) -}}
{{- if .Values.orchestration.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ include "camundaPlatform.fullname" . }}-grpc
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.global.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.tplvalues.merge-overwrite" (dict
      "values" (list
        (include "camundaPlatform.labels" .)
        .Values.global.gateway.labels
      )
      "context" .
    ) | nindent 4 }}
spec:
  parentRefs:
  - name: {{ include "camundaPlatform.fullname" . }}
    sectionName: {{ if .Values.global.gateway.tls.enabled }}grpcs{{ else }}grpc{{ end }}
  hostnames:
  - {{ tpl .Values.orchestration.ingress.grpc.host $ }}
  rules:
  - backendRefs:
    - name: {{ include "orchestration.serviceName" . }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.orchestration.service.grpcPort }}
{{- end }}
{{- end }}
