#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: latest
    digest: "sha256:5052037474332386e4ca2cb8d8e57f55e06cb48bdccf2a09c352999c69c92624"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.8.7
    digest: "sha256:60794b501137b04477baf3be3b87c29db975e542b60463e59863626fbaa44203"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.8.5
    digest: "sha256:442279d0e13977ab1ba25ce01ebe145ceeca0019a8701e6217209e50c1075fbe"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: 8.8
      digest: "sha256:0755964b91066aaf1d5c6ef65c97a193944aab5d268d63aff77901f234322d67"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: 8.8
      digest: "sha256:ee5e5ea2777c3102c7a7a5b35535369bec18b538f7765778d50205f0475d8dd5"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: 8.8
      digest: "sha256:c0db5c54a1ce76c4ae5588a4c9f57f7a3687b52220bef8b2ceace60f0d7e8c62"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.8.12
    digest: "sha256:b2ef7d2a690491ef8b5b6f8acb97ee284309fd94b8c7ea605cf8005f998014aa"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.8.7
    digest: "sha256:9de4d120f73592a6e45b4467ac769935611acf7822e69acd2109d93af862396c"
