apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: camunda-gateway
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    port: 8023
    protocol: HTTP
    hostname: "local.distro.ultrawombat.com"
