{{- if and .Values.global.gateway.enabled (not .Values.global.gateway.external) (.Values.global.gateway.createGatewayResource) -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "camundaPlatform.fullname" . }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.global.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  gatewayClassName: {{ .Values.global.gateway.className }}
  listeners:
  {{- if .Values.global.gateway.tls.enabled }}
  - name: https
    port: 443
    protocol: HTTPS
    hostname: {{ tpl .Values.global.gateway.hostname $ }}
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: {{ .Values.global.gateway.tls.secretName }}
  {{- else }}
  - name: http
    port: {{ if .Values.global.gateway.tls.enabled }}443{{ else }}80{{ end }}
    protocol: HTTP
    hostname: {{ tpl .Values.global.gateway.hostname $ }}
  {{- end }}
{{- end }}
