{{- if and .Values.global.gateway.enabled (not .Values.global.gateway.external) -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "camundaPlatform.fullname" . }}
spec:
  gatewayClassName: {{ .Values.global.gateway.className }}
  listeners:
  - name: http
    port: {{ if .Values.global.gateway.tls.enabled }}443{{ else }}80{{ end }}
    protocol: HTTP
    hostname: {{ .Values.global.gateway.hostname }}
{{- end }}
