{{- if and .Values.global.gateway.enabled (not .Values.global.gateway.external) (.Values.global.gateway.createGatewayResource) -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "camundaPlatform.fullname" . }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.global.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.tplvalues.merge-overwrite" (dict
      "values" (list
        (include "camundaPlatform.labels" .)
        .Values.global.gateway.labels
      )
      "context" .
    ) | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.global.gateway.className }}
  listeners:
  {{- if .Values.global.gateway.tls.enabled }}
  - name: https
    port: 443
    protocol: HTTPS
    hostname: {{ tpl .Values.global.host $ }}
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: {{ .Values.global.gateway.tls.secretName }}
  {{- if .Values.orchestration.gateway.grpc.enabled }}
  - name: grpcs
    port: 443
    protocol: HTTPS
    hostname: {{ tpl .Values.orchestration.gateway.grpc.host $ }}
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: {{ .Values.global.gateway.tls.secretName }}
  {{- end }}
  {{- else }}
  - name: http
    port: 80
    protocol: HTTP
    hostname: {{ tpl .Values.global.host $ }}
  {{- if .Values.orchestration.gateway.grpc.enabled }}
  - name: grpc
    port: 80
    protocol: HTTP
    hostname: {{ tpl .Values.orchestration.gateway.grpc.host $ }}
  {{- end }}
  {{- end }}
{{- end }}
