{{- if and .Values.global.gateway.enabled (not .Values.global.gateway.external) -}}
kind: ReferenceGrant
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ include "camundaPlatform.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.global.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.tplvalues.merge-overwrite" (dict
      "values" (list
        (include "camundaPlatform.labels" .)
        .Values.global.gateway.labels
      )
      "context" .
    ) | nindent 4 }}
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: {{ .Values.global.gateway.controllerNamespace | default .Release.Namespace }}
  - group: gateway.networking.k8s.io
    kind: GRPCRoute
    namespace: {{ .Values.global.gateway.controllerNamespace | default .Release.Namespace }}
  to:
  - group: ""
    kind: Service
{{- end }}
