{{- if .Values.orchestration.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestration.serviceNameBroker" . }}
  labels:
    {{- include "orchestration.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.annotations }}
      {{- toYaml .Values.global.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.orchestration.service.annotations }}
      {{ .Values.orchestration.service.annotations | toYaml | nindent 4 }}
    {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  type: {{ .Values.orchestration.service.type }}
  ports:
    - port: {{ .Values.orchestration.service.internalPort }}
      protocol: TCP
      name: {{ default "internal" .Values.orchestration.service.internalName  }}
    - port: {{ .Values.orchestration.service.commandPort }}
      protocol: TCP
      name: {{ default "command" .Values.orchestration.service.commandName }}
    - port: {{ .Values.orchestration.service.managementPort }}
      protocol: TCP
      name: {{ default "management" .Values.orchestration.service.managementName }}
    {{- if .Values.orchestration.service.extraPorts }}
    {{ .Values.orchestration.service.extraPorts | toYaml | nindent 4 }}
    {{- end }}
  selector:
    {{- include "orchestration.matchLabels" . | nindent 4 }}
{{- end }}
