apiVersion: v2
appVersion: "1.2.9"
description: Zeebe Cluster + Operate Helm Chart for Kubernetes
name: zeebe-full-helm
version: 1.2.11
type: application
icon: https://helm.camunda.io/imgs/zeebe-logo.png
dependencies:
- name: zeebe-cluster-helm
  repository: https://camunda-community-hub.github.io/camunda-cloud-helm/
  version: 1.2.13
- name: zeebe-operate-helm
  repository: https://camunda-community-hub.github.io/camunda-cloud-helm/
  version: 1.2.8
- condition: tasklist.enabled
  name: zeebe-tasklist-helm
  repository: https://camunda-community-hub.github.io/camunda-cloud-helm/
  version: 1.2.7
- name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 3.19.0
annotations:
  artifacthub.io/changes: |
    - bump tasklist chart version to 1.2.6
    - bump operate chart version to 1.2.7
    - bump cluster chart version to 1.2.12
  artifacthub.io/containsSecurityUpdates: "true"
