{{- if .Values.identity.migration.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-migration-configuration
  namespace: hamza
data:
  application.yaml: |
    camunda:
      migration:
        identity:
          mode: {{ .Values.connectors.livenessProbe.failureThreshold }}
          cluster:
            cluster-name: {{ tpl .Values.global.zeebeClusterName . }}
            cluster-size: {{ .Values.core.clusterSize }}
            partitions-count: {{ .Values.core.partitionCount }}
            replication-factor: {{ .Values.core.replicationFactor }}
            initial-contact-points:
            {{- range (untilStep 0 (int .Values.core.clusterSize) 1) }}
              - {{ include "core.legacyName" $ }}-{{ . }}.${K8S_SERVICE_NAME}:{{$.Values.core.service.internalPort}}
            {{- end }}
          management-identity:
            audience: {{ include "identity.authAudience" . | quote }}
            base-url: {{ tpl .Values.global.identity.auth.identity.redirectUrl $ | quote }}
            client-id: {{  printf "%s" (include "identity.authClientId" .) | default "camunda-identity" | quote }}
            client-secret: ${VALUES_CAMUNDA_MIGRATION_IDENTITY_MANAGEMENTIDENTITY_CLIENTSECRET:}
            issuer-backend-url: {{ include "camundaPlatform.authIssuerBackendUrl" . | quote }}
{{- end }}
