{{- if .Values.identity.migration.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identity.fullname" . }}-migration-configuration
data:
  application.yaml: |
    camunda:
      migration:
        identity:
          mode: {{ .Values.global.identity.auth.type }}
          cluster:
            cluster-name: {{ tpl .Values.global.zeebeClusterName . }}
            cluster-size: {{ .Values.core.clusterSize }}
            partitions-count: {{ .Values.core.partitionCount }}
            replication-factor: {{ .Values.core.replicationFactor }}
            initial-contact-points:
            {{- range (untilStep 0 (int .Values.core.clusterSize) 1) }}
              - {{ include "core.legacyName" $ }}-{{ . }}.{{ include "core.fullname" $ }}:{{$.Values.core.service.internalPort}}
            {{- end }}
          management-identity:
            audience: {{ include "identity.authAudience" . | quote }}
            base-url: {{ tpl .Values.global.identity.auth.identity.redirectUrl $ | quote }}
            client-id: migration
            client-secret: ${VALUES_CAMUNDA_IDENTITY_CLIENT_SECRET:}
            issuer-backend-url: {{ include "camundaPlatform.authIssuerBackendUrl" . | quote }}
{{- end }}
