{{- if .Values.identity.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "identityMigration.fullname" . }}
  labels: {{- include "identityMigration.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "identityMigration.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      imagePullSecrets: {{- include "core.imagePullSecrets" . | nindent 8 }}
      # TODO: Add an initContainer to wait for the core pod to start. No need to wait for the management identity because the core relies on management identity.
      {{- if .Values.core.podSecurityContext }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" $.Values.core.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: camunda-migration
          # TODO: CHANGE TO A SPECIFIC VERSION
          image: camunda/camunda:SNAPSHOT
          # image: {{ include "camundaPlatform.imageByParams" (dict "base" .Values.global "overlay" .Values.core) }}
          imagePullPolicy: Always
          # imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- if .Values.core.containerSecurityContext }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" $.Values.core.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: VALUES_CAMUNDA_IDENTITY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "core.authClientSecretName" . }}
                  key: {{ include "core.authClientSecretKey" . }}
          command:
            - /usr/local/camunda/bin/identity-migration
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - name: config
              mountPath: /usr/local/camunda/config/application.yaml
              subPath: application.yaml
      volumes:
        - name: config
          configMap:
            name: identity-migration-configuration
{{- end }}
