#
# Camunda - Latest
#

global:
  # https://github.com/camunda/camunda-platform/releases
  # https://hub.docker.com/u/camunda
  image:
    tag:

  identity:
    image:
      repository: camunda/identity
      tag: 8.5.8

console:
  # Camunda Enterprise repository.
  # registry.camunda.cloud/console
  image:
    # renovate: datasource=docker depName=camunda/console lookupName=registry.camunda.cloud/console/console-sm
    tag: 8.5.113

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.5.10

operate:
  # https://hub.docker.com/r/camunda/operate/tags
  image:
    tag: 8.5.4

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.5.8

tasklist:
  # https://hub.docker.com/r/camunda/tasklist/tags
  image:
    tag: 8.5.2

webModeler:
  # Camunda Enterprise repository.
  # registry.camunda.cloud/web-modeler-ee
  image:
    # renovate: datasource=docker depName=camunda/web-modeler lookupName=registry.camunda.cloud/web-modeler-ee/modeler-restapi
    tag: 8.5.11

zeebe:
  # https://hub.docker.com/r/camunda/zeebe/tags
  image:
    tag: 8.5.3

zeebeGateway:
  # https://hub.docker.com/r/camunda/zeebe/tags
  image:
    tag: 8.5.3

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    tag: 8.5.5

identityKeycloak:
  # https://hub.docker.com/r/bitnami/keycloak/tags
  image:
    repository: bitnami/keycloak
    tag: 23.0.7
  postgresql:
    # https://hub.docker.com/r/bitnami/postgresql/tags
    image:
      repository: bitnami/postgresql
      tag: 15.8.0-debian-12-r23

#
# Elasticsearch
#

elasticsearch:
  # https://hub.docker.com/r/bitnami/elasticsearch/tags
  image:
    repository: bitnami/elasticsearch
    tag: 8.12.2
