name: Release Charts

on:
  # Allow to run the workflow from GitHub UI and other workflows.
  workflow_dispatch:
  push:
    branches:
      - main

env:
  HELM_VERSION: 3.6.3

jobs:
  generate-charts-release-notes:
    runs-on: ubuntu-latest
    container: quay.io/git-chglog/git-chglog:0.15.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Install dependencies
        run: |
          apk add bash grep yq

      - name: Generate charts release-notes
        shell: bash
        run: |
          set -x
          helm repo add camunda https://helm.camunda.io
          for chart_file in charts/*/Chart.yaml; do
              chart_name=$(grep -Po "(?<=^name: ).+" ${chart_file})
              chart_version=$(grep -Po "(?<=^version: ).+" ${chart_file})

              chart_version_status=$(helm search repo camunda/${chart_name} --version ${chart_version})

              if [[ ${chart_version_status} == 'No results found' ]]; then
                  bash scripts/generate-release-notes.sh "${chart_file}"
              fi
          done

      - name: Stash generated charts release-notes files
        uses: actions/upload-artifact@v2
        with:
          name: charts-generated-release-notes
          path: |
            charts/*/RELEASE-NOTES.md
            charts/*/Chart.yaml

  release:
    needs: generate-charts-release-notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Unstash generated charts release-notes files
        uses: actions/download-artifact@v2
        with:
          name: charts-generated-release-notes
          path: charts
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: "${{ env.HELM_VERSION }}"
      - name: Add helm repos
        run: |
          helm repo add elastic https://helm.elastic.co
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
      - name: Get Helm Deps
        run: make deps
      - name: Run tests
        run: make test
      - name: Run Chart Releaser
        uses: helm/chart-releaser-action@v1.3.0
        with:
          config: .github/config/chart-releaser.yaml
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          CR_SKIP_EXISTING: 'true'
