# Basic test for older Camunda Platform 8 Helm charts.
name: "Test - Regression"

on:
  push:
    paths:
    - 'charts/camunda-platform/values/values-v8*.yaml'
  pull_request:
    paths:
    - 'charts/camunda-platform/values/values-v8*.yaml'
  workflow_dispatch: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CAMUNDA_DISTRO_TEST_DELETE_NAMESPACE: ${{ !secrets.ACTIONS_STEP_DEBUG }}
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  GITHUB_WORKFLOW_RUN_ID: ${{ github.run_id }}
  KUBECONFIG: .github/config/kubeconfig

jobs:
  test:
    name: Previous chart v${{ matrix.camundaChart }}.x
    if: ${{ contains(github.event.*.labels.*.name, 'test-regression') || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        camundaChart:
        - "8.1"
        - "8.0"
    steps:
    - uses: actions/checkout@v3
    - name: Login to GKE
      uses: ./.github/actions/gke-login
      with:
        cluster-name: ${{ secrets.GKE_CLUSTER }}
        cluster-location: ${{ secrets.GKE_ZONE }}
        workload-identity-provider: ${{ secrets.GCP_AUTH_WORKLOAD_IDENTITY_PROVIDER }}
        service-account: ${{ secrets.GCP_AUTH_SERVICE_ACCOUNT }}
    - name: Set test vars
      id: vars
      run: |
        TEST_NAMESPACE="camunda-platform-pr-$GITHUB_PR_NUMBER-regression-${{ matrix.camundaChart }}"
        echo "TEST_NAMESPACE=${TEST_NAMESPACE//./-}" >> $GITHUB_ENV
    - name: Install env dependencies
      uses: asdf-vm/actions/install@v2
    - name: Cleanup any old namespace
      run: |
        kubectl delete ns $TEST_NAMESPACE --ignore-not-found=true
    - name: Add Camunda Platform 8 Helm chart repo
      run: |
        helm repo add camunda https://helm.camunda.io
    - name: Install Camunda Platform 8 Helm chart v${{ matrix.camundaChart }}
      timeout-minutes: 15
      run: |
        helm install camunda-platform camunda/camunda-platform \
          --wait --timeout 15m0s \
          --version ${{ matrix.camundaChart }} \
          --namespace $TEST_NAMESPACE --create-namespace \
          --values charts/camunda-platform/values/values-v${{ matrix.camundaChart }}.yaml
    - name: Check setup
      if: always()
      run: |
        echo "List Helm release ..."
        helm list -n $TEST_NAMESPACE
        echo "Get Pods ..."
        kubectl get pod -n $TEST_NAMESPACE
        echo "Describe Pods ..."
        kubectl describe pod -n $TEST_NAMESPACE
    - name: Cleanup test namespace
      if: always() && env.CAMUNDA_DISTRO_TEST_DELETE_NAMESPACE != 'false'
      run: |
        kubectl delete ns $TEST_NAMESPACE --ignore-not-found=true
