apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "optimize.fullname" . }}
  labels: {{- include "optimize.labels" . | nindent 4 }}
  annotations: {{- toYaml  .Values.global.annotations | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "optimize.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: 
        {{- include "optimize.labels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
        {{- include "camundaPlatform.imagePullSecrets" . | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        {{- if .Values.image.tag }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.global.image.tag }}"
        {{- end }}
        env:
          - name: CAMUNDA_OPTIMIZE_ZEEBE_ENABLED
            value: "true"
          - name: CAMUNDA_OPTIMIZE_ZEEBE_PARTITION_COUNT
            value: {{ .Values.partitionCount | quote }}
          - name: OPTIMIZE_ELASTICSEARCH_HOST
            value: {{ .Values.global.elasticsearch.host | quote }}
          - name: OPTIMIZE_ELASTICSEARCH_HTTP_PORT
            value: {{ .Values.global.elasticsearch.port | quote }}
          - name: SPRING_PROFILES_ACTIVE
            value: "ccsm"
          - name: CAMUNDA_OPTIMIZE_IDENTITY_ISSUER_URL
            value: {{ .Values.global.identity.auth.publicIssuerUrl | quote }}
          - name: CAMUNDA_OPTIMIZE_IDENTITY_ISSUER_BACKEND_URL
            value: "http://{{ include "common.names.dependency.fullname" (dict "chartName" "keycloak" "chartValues" . "context" $) | trunc 20 | trimSuffix "-" }}:80/auth/realms/camunda-platform"
          - name: CAMUNDA_OPTIMIZE_IDENTITY_CLIENTID
            value: "optimize"
          - name: CAMUNDA_OPTIMIZE_IDENTITY_CLIENTSECRET
            {{- if and .Values.global.identity.auth.optimize.existingSecret (not (typeIs "string" .Values.global.identity.auth.optimize.existingSecret)) }}
            valueFrom:
              secretKeyRef:
                {{- /*
                    Helper: https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_secrets.tpl
                    Usage in keycloak secrets https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/secrets.yaml
                    and in statefulset https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/statefulset.yaml
                */}}
                name: {{ include "common.secrets.name" (dict "existingSecret" .Values.global.identity.auth.optimize.existingSecret "context" $) }}
                key: optimize-secret
            {{- else }}
            valueFrom:
              secretKeyRef:
                name: {{ include "identity.secretNameOptimizeIdentity" . }}
                key: optimize-secret
            {{- end }}
          - name: CAMUNDA_OPTIMIZE_IDENTITY_AUDIENCE
            value: "optimize-api"
          - name: CAMUNDA_OPTIMIZE_SECURITY_AUTH_COOKIE_SAME_SITE_ENABLED
            value: "false"
          - name: CAMUNDA_OPTIMIZE_UI_LOGOUT_HIDDEN
            value: "true"
          {{- if .Values.env}}
          {{ .Values.env | toYaml | nindent 10 }}
          {{- end }}
        {{- if .Values.command}}
        command: {{ .Values.command }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: 8090
          name: http
          protocol: TCP
        volumeMounts:
        {{- if .Values.extraVolumeMounts}}
          {{- .Values.extraVolumeMounts | toYaml | nindent 8 }}
        {{- end }}
      volumes:
      {{- if .Values.extraVolumes}}
      {{- .Values.extraVolumes | toYaml | nindent 6 }}
      {{- end }}
      {{- if .Values.serviceAccount.name}}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
