#
# Camunda Helm chart.
#

global:
  # https://github.com/camunda/camunda/releases
  # https://hub.docker.com/u/camunda
  image:
    tag:

console:
  # Camunda Enterprise repository.
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.7.59

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.7.8

operate:
  # https://hub.docker.com/r/camunda/operate/tags
  image:
    repository: camunda/operate
    tag: 8.7.11

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.7.8

tasklist:
  # https://hub.docker.com/r/camunda/tasklist/tags
  image:
    repository: camunda/tasklist
    tag: 8.7.11

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi
  image:
    # renovate: datasource=docker depName=camunda/web-modeler-restapi
    tag: 8.7.8

zeebe:
  # https://hub.docker.com/r/camunda/zeebe/tags
  image:
    repository: camunda/zeebe
    tag: 8.7.11

zeebeGateway:
  # https://hub.docker.com/r/camunda/zeebe/tags
  image:
    repository: camunda/zeebe
    tag: 8.7.11

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.7.6

identityKeycloak:
  # https://hub.docker.com/r/bitnami/keycloak/tags
  image:
    repository: bitnamilegacy/keycloak
    tag: 26.3.3
  postgresql:
    # https://hub.docker.com/r/bitnami/postgresql/tags
    image:
      repository: bitnamilegacy/postgresql
      tag: 15.10.0-debian-12-r2

#
# Elasticsearch
#

elasticsearch:
  # https://hub.docker.com/r/bitnami/elasticsearch/tags
  image:
    repository: bitnamilegacy/elasticsearch
    tag: 8.17.4
