#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.9-SNAPSHOT
    digest: "sha256:fd2f22c0db21ee08ba74a10dba1ab9e0513b2e2bd974228afa140ba9eaad6e55"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: SNAPSHOT
    digest: "sha256:adcbf32d8a2d23a6f9f307cdcb7b313eb6c7768abd88e43c3b9d1a3f1e3fbe8f"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8-latest
    digest: "sha256:442279d0e13977ab1ba25ce01ebe145ceeca0019a8701e6217209e50c1075fbe"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:46385e25b0bc34b669d88df316bc15e13024c97eb10aefd171f1b2c92b9e7dc0"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: SNAPSHOT
      digest: "sha256:b69199b79235ff5b2f44a76a8c3a4198cb05c8d1c9ac5d57de0c17deeab79e44"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:f607972743c3f7ccb6e1f5eda3d72d83d24666061fbc84abd62a75df855ed1d3"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: SNAPSHOT
    digest: "sha256:28415cbbda18fc255940e7c186e7ece33f0aa0049e65f4598b005f923b34359f"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:48627aa8557afa8e396876245bcbb31b07f0a4255f1950625610a563cf9c5bbd"
