#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.9-SNAPSHOT
    digest: "sha256:bd1f24379f55be2dabe90b827394a57b3cfe23171ddf28fa386fb3294f87bd96"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: SNAPSHOT
    digest: "sha256:c8c503342d6f20602c28d2773d7172b7dde9b5ae41ac8941616a962b7f8d9ee2"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8-latest
    digest: "sha256:15c172742ee53cc680b23fd5069dfc43f71070d09230ba11c34b45d24e603469"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:379f537289ba5a5318e84612939ec232291f65dcdef54ea7b73c0a7dc94cd483"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: SNAPSHOT
      digest: "sha256:a4fd9f966fd1e8ac880be83b8f4554665d8e2f3136f8cdff9b735c7d7dec5180"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:f3c6d3b0a10141a09f977302778fc9b4e9fdf5ffeee67001dc3bec89b1c666cf"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: SNAPSHOT
    digest: "sha256:a0b51091a6c0f240962e0e65e19d50c6e6afa6f3b2d300e30e22086a9aa2c759"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:cb92bd7e8bed60df5b263332889711ef3a4c9db1c8b3aeb18a680abfd5264c07"
