#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.9-SNAPSHOT
    digest: "sha256:f310967b71aaa8e780237ae5ca02c3bc941ba37e4cb37373b6ec690612418a2e"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: SNAPSHOT
    digest: "sha256:121fea2839b1e8c7a190f07e4dbc8e715da7c16ba9ecd1cd51d210a78c4e2f7c"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8-latest
    digest: "sha256:ee002dd212ddababaa2a6d09039e64b10e4ffc318f7a7721981f2b829bb14dd8"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:3b04f171f212dd36830ab20c33fceb22a61bd35449be80a8615bf618d269419a"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: SNAPSHOT
      digest: "sha256:3c926f11f7cdb42ec07466f1336eed5aa899d6afd6f151959b6190e86a933f74"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:45b602c0e171c1f3f880fedd4d91f3206fbd73afdb5522b5e7a7d13b527714be"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: SNAPSHOT
    digest: "sha256:fd9cccff8b56a28cb3f1d3c478e9ef4dad80d9ffbc67f769510a5415aee6b2eb"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:aef65a501b0e4e1aa16d0a03feebe51dec41ec7dcac2d821371829501ba1bc0a"
