#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.9-SNAPSHOT
    digest: "sha256:e90ad20bbc936ab123a4343a1a3cf88e4cd839b22a2c5b5dedfcc7b5b478c659"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: SNAPSHOT
    digest: "sha256:d4b0fb0740084382962cdc833c2968b381ba8223a8940983024f0baab1af25db"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8-latest
    digest: "sha256:2b4350b56d177c3cf027f71083bbf0d1f1311fcebafaa01afedc8ddbce639323"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:f4c2a144dbf88c89b00c3e661cb976099db6dddf9f29ec797d476ba1ae7358c6"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: SNAPSHOT
      digest: "sha256:b1fd084058d3c981857b79da689c8799f7b71c3a2be374d6fd5a344126296ad8"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:4a3f95e5cb287f71de454f5bb4f31dcabeec1aabc960d77226d83a477f83882a"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: SNAPSHOT
    digest: "sha256:0a0a7e0a59ed134729fbaf45311d3ed7630c8da20f2302925449082670d3ce7a"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:7a9f6acf6098e3599e28267f560713a30aa67bf477b7a593d7d54199bd9d754e"
